version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: kakeboDB
      MYSQL_USER: kakeappuser
      MYSQL_PASSWORD: kakeapppassword
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  springboot:
    build: .
    container_name: springboot
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/kakeboDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: kakeappuser
      SPRING_DATASOURCE_PASSWORD: kakeapppassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql-data: