INSERT INTO expense_entity (expense_category, expense_date, expense_amount, expense_description, expense_user_id)
VALUES
    ('SUPERVIVENCIA', '2024-05-01', 100.00, 'Descripción del gasto 2', 'daniel'),
    ('OCIO_Y_VICIO', '2024-05-02', 200.00, 'Descripción del gasto 3', 'tania'),
    ('CULTURA', '2024-05-03', 300.00, 'Descripción del gasto 4', 'tania'),
    ('EXTRAS', '2024-05-04', 400.00, 'Descripción del gasto 5', 'tamar'),
    ('SUPERVIVENCIA', '2024-05-05', 500.00, 'Descripción del gasto 6', 'tania'),
    ('OCIO_Y_VICIO', '2024-05-06', 600.00, 'Descripción del gasto 7', 'tamar'),
    ('CULTURA', '2024-05-07', 700.00, 'Descripción del gasto 8', 'tania'),
    ('EXTRAS', '2024-05-08', 800.00, 'Descripción del gasto 9', 'daniel'),
    ('SUPERVIVENCIA', '2024-05-09', 900.00, 'Descripción del gasto 10', 'tania');